rootProject.name = "MindOverCNC Lathe"
include("compose")
include("repository")
include("database")
include("impl")
include("editor")
include("logger")
include("model")
include("dispatcher")
include("protos")
include("grpc")
include("ktlcnc")
include("ktlcnc:model")
//include("vtk")

//include("localization")
