/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mindovercnc_linuxcnc_StatusReader */

#ifndef _Included_com_mindovercnc_linuxcnc_StatusReader
#define _Included_com_mindovercnc_linuxcnc_StatusReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mindovercnc_linuxcnc_StatusReader
 * Method:    getString
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mindovercnc_linuxcnc_StatusReader_getString
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mindovercnc_linuxcnc_StatusReader
 * Method:    readStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mindovercnc_linuxcnc_StatusReader_readStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_mindovercnc_linuxcnc_StatusReader
 * Method:    init
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_mindovercnc_linuxcnc_StatusReader_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
