/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mindovercnc_linuxcnc_HalHandler */

#ifndef _Included_com_mindovercnc_linuxcnc_HalHandler
#define _Included_com_mindovercnc_linuxcnc_HalHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mindovercnc_linuxcnc_HalHandler
 * Method:    createComponent
 * Signature: (Ljava/lang/String;)Lcom/mindovercnc/linuxcnc/HalComponent;
 */
JNIEXPORT jobject JNICALL Java_com_mindovercnc_linuxcnc_HalHandler_createComponent
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
