/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mindovercnc_linuxcnc_ErrorReader */

#ifndef _Included_com_mindovercnc_linuxcnc_ErrorReader
#define _Included_com_mindovercnc_linuxcnc_ErrorReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mindovercnc_linuxcnc_ErrorReader
 * Method:    fetchMessage
 * Signature: ()Lcom/mindovercnc/linuxcnc/model/SystemMessage;
 */
JNIEXPORT jobject JNICALL Java_com_mindovercnc_linuxcnc_ErrorReader_fetchMessage
  (JNIEnv *, jobject);

/*
 * Class:     com_mindovercnc_linuxcnc_ErrorReader
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mindovercnc_linuxcnc_ErrorReader_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
