/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mindovercnc_linuxcnc_HalComponent */

#ifndef _Included_com_mindovercnc_linuxcnc_model_HalComponent
#define _Included_com_mindovercnc_linuxcnc_model_HalComponent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mindovercnc_linuxcnc_HalComponent
 * Method:    addPin
 * Signature: (Lcom/mindovercnc/linuxcnc/model/HalPin;)I
 */
JNIEXPORT jobject JNICALL Java_com_mindovercnc_linuxcnc_model_HalComponent_addPin
  (JNIEnv *, jobject, jstring, jobject, jobject);

JNIEXPORT void JNICALL Java_com_mindovercnc_linuxcnc_model_HalComponent_setReady
(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
